name: Password Manager APK Yap

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle Kurulumu (Sistem Geneli)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Zip Kontrolu ve Otomatik Acma
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          if [ -n "$ZIP_FILE" ]; then
            echo "Bulunan zip dosyası açılıyor: $ZIP_FILE"
            unzip -o "$ZIP_FILE" -d .
          else
            echo "Kök dizinde herhangi bir .zip dosyası bulunamadı, doğrudan klasörlerle devam ediliyor."
          fi

      - name: Debug Keystore Olustur
        run: |
          keytool -genkey -v -keystore ./debug.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias androiddebugkey -storepass android -keypass android -dname "CN=Debug, OU=Debug, O=Debug, L=Debug, S=Debug, C=US"
      
      - name: APK Olustur (Build)
        run: |
          SETTINGS_DIR=$(find . -name "settings.gradle*" -exec dirname {} \; | head -n 1)
          
          if [ -n "$SETTINGS_DIR" ]; then
            echo "Proje kök dizini bulundu: $SETTINGS_DIR"
            cd "$SETTINGS_DIR"
          else
            echo "HATA: settings.gradle dosyası hiçbir yerde bulunamadı!"
            exit 1
          fi
          
          echo "Derleme başlatılıyor. Şu anki Konum: $(pwd)"
          gradle assembleDebug
        env:
          JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
      
      - name: APK'yi Cikti Olarak Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: webnetik-pass-apk
          path: "**/*.apk"
          if-no-files-found:  error
